language: python
python:
- '2.7'
sudo: false
install: pip install .
script: python setup.py nosetests
deploy:
  provider: pypi
  user: github-ll
  password:
    secure: sN+6KTSntauGMvz6JEqXjcMGizdL1J/X149ChTk+s32w5yl1NsQXhWLUgCTpD4GdAfFKnTz9CKfFKcrS3dy/FI6ugBPVLkofn88P5AzUJowcy43JlAouULZnTKCFUfLf+ru5g5gVsY0rE+4wTJLzA3aLTvpRA+9TMUONdil8bvZoaLNHQTyU+zAUY+4FmYckyZ24tYDX1Wddq981b3k9NxN+LLpUqw8Oop6sSB7jLCjeXxcpFv8LmjoskSkx6BgcJUe2PRCjvnv72tRlV1GKR95WxsQziTIdsEKBRvQU9VwRi0SccfdZOf2DeqPAxvaTPyyPMc4rt/BVj97V1KWVz4pvzGBGqG2t6QNpl7h+KjxbpFTBdYnyys3pcMvgba8V+xvCCZ7EhaS+FveLTdA90QEMgbl3he+3t4XazA62I9/UVJ3mFLQnoZcSEOP3/7YRJCTOduZc9LxaTKImHgfoP7Rqt8WlMPmdfhEd8qMt2vbC20wcE/e4BOoNQzoSTWLMnCefcJZRw5nmAvpMz1o8jhE54QMQAWw8LGx3MN2dpoEpp3VYzOcjWZ/N/T95yr37yz+WmHaBtD8MwhyZdvzKJnr0UY7PRCDN3qYIsNrcdpMxFjyYjEoc5BmlDTkblWOO9ftSrYFPF2XvVUMrHYcAPHI0YZE7vyTOS4LrvuhFlrU=
  on:
    tags: true
    repo: locationlabs/aws-code-deploy
