language: python
python:
- '2.7'
sudo: false
install: pip install .
script: python setup.py nosetests
deploy:
  provider: pypi
  user: jessemyers
  password:
    secure: T5XlrWLMTtIcLz5se8MZl5xW6JMTNErg+23iBxCuoxr6o29ZVCgrHn0lYvWX2ViMBKm1J4qm6NaVii9S0tRrpx8u087kCJhAlkfW06b8M4bbHO/7figPePIRYK6dw1wDhR91VZXObgrdsthmCBsgtaUK3lj3ubsKfDcIEI0CS0BOZV4fF/1xkEs2IvfWEifajvXCXBQkvZ1VCZCsBcnIQjrcpS/huv217Ui+63MJcpi4nh+Ou+t+NjckNIrSEg1prPrSz698JM6JSRGKMOzq2RDgu4jaBf/mqxt+WYJm4u1/7KBOS4ZoHZtuodkXcqpQr/5FF0Azo/WuBlK12euSf34ygHHeWGSE4xdjimbjUgk79wEnaDXwUqzQd51WhIoSwR1obTF27AEQnshN1vFJfw1S5/0wkYzpUeHk0iowNqCvRRxgngebY3+RhTHhNQtVs0/qg/8rBxx7S2d2cAyS+IXTNtxxQvxFX+pz0E6Z/v2eLi5VgKmUy7qA9ugNcf1LH6RhDqn/lDYR+KgqCU0qKIh5nbiawUi/x0j8Qule3b9kheXICNDoPWPO+wvGF6hnmSb5Emuv+5qxHdRWl3iPcB/VDMqDOtBHXrgiBkTiKNvZwauLqDN7KEYsjvdv73zSClzp+339lliDqfipnB2fBKjqKQCiUsL5kTl5G3Ds4Kk=
  on:
    tags: true
    repo: locationlabs/aws-code-deploy
